---
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
install:
  - pip install -r requirements.txt
# Since we have no tests yet, try to install the package and execute the
# default actions
script:
  - python setup.py install
  - python -m pandas_metricsreader.graphite.graphite
  - python -m pandas_metricsreader.PNP4Nagios.pnp4nagios
