---
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
# Since we have no tests yet, try to install the package and execute the
# default actions
script:
  - pytest --cov pandas_metricsreader --cov-report term --cov-report html tests
